### ISSUE TITLE
NoClassDefFoundError using packaged jar

### ISSUE THREAD

**Issue by jimirocks** [martiner/gooddata-shell#9]
When I build from master using `mvn package` and run it with `java -jar` I get:
```
gdsh> login --user gooddata2@zendesk.com --pass password --host analytics.zendesk.com
Command failed java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
Exception in thread "Spring Shell" java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager     
```

However `mvn exec:java` works as expected

**Comment by martiner** [comment]
Hm, I have sometimes experienced this issue when running `mvn compile exec:java` while running this two goals separately works as expected.
